#!/bin/bash

# ================================================================
# CLYDE : Clyde Lets You Do Everything
#
#                 ((   )  (
#               ( (   )(( (   )
#             )    ) ( )) )( (( )
#             ( (((   )  (  )  ) )
#            )) (( ) (          ((
#           (  )) )  ____   ____ )
#            ) ( ) `|<();|-|,()>|
#           ( ))(    `--'  \`--'
#           )( ( )       (- )   )
#             ))        _____  /
#               )   `     --  /
#                     `   __,
#
# I help you keep track of the random personal projects you have
# and suggest to you to do one of them.
#
# Do all the things you want to do, and don't forget to
# continually improve yourself!
#
# By Jansen Price <jansen.price@gmail.com>
# Date: 2017-12-07
# ================================================================

VERSION="clyde-1.1"
CLYDE_PATH=~/.clyde
CLYDE_PROJ_FILE=$CLYDE_PATH/projects.txt
SHOW_CLYDE=true
WIDTH=`tput cols`

if [ ! -d "$CLYDE_PATH" ]; then
    mkdir "$CLYDE_PATH"
fi

green() {
    if [ -t 0 ]; then
        printf "\E[32m"
    fi
}
op() {
    if [ -t 0 ]; then
        printf "\E[39;49m"
    fi
}

showclyde() {
    green
    echo '                 ((   )  ('
    echo '               ( (   )(( (   )'
    echo '             )    ) ( )) )( (( )'
    echo '             ( (((   )  (  )  ) )'
    echo '            )) (( ) (          (('
    echo '           (  )) )  ____   ____ )'
    echo '            ) ( ) `|<();|-|,()>|'
    echo '           ( ))(    `--'"'"'  \`--'"'"
    echo '           )( ( )       (- )   )'
    echo '             ))        _____  /'
    echo '               )   `     --  /'
    echo '                     `   __,'
    echo
    op
}

# Function for displaying horizontal rule
# First argument is the char to repeat
hr() {
    start=1
    let "end=$WIDTH-1"
    for ((i=$start; i<=$end; i++)); do echo -n $1; done
    echo $1
}

# Function for displaying usage
displayUsage() {
    echo "$VERSION ~ Clyde Lets You Do Everything"
    echo
    echo "Usage: clyde [-n] <command> [arguments]"
    echo
    echo "Options:"
    echo "  -n : Will hide the clyde mascot when suggesting a project/task"
    echo
    echo "Commands:"
    echo "  add <item> : Add a project/task"
    echo "  list : List all current project/tasks"
    echo "  suggest : Suggest a project/task to work on"
    echo "  manage : Open tasks in editor to modify manually"
}

# Handle --help arg
if [ -n "$1" -a "$1" == "--help" ]; then
    displayUsage
    exit 1
fi

# Handle --version arg
if [ -n "$1" -a "$1" == "--version" ]; then
    echo $VERSION
    exit 1
fi

# Handle -n flag
if [ -n "$1" -a "$1" == "-n" ]; then
    SHOW_CLYDE=false
    shift
fi

# Shift off the used args
shift $((OPTIND-1))

COMMAND="suggest"
if [ -n "$1" ]; then
    COMMAND="$1"
fi

# COMMAND: add
if [ $COMMAND == "add" ]; then
    shift

    # Get message
    if [ -z "$1" ]; then
        echo Missing argument
        exit 2
    fi

    # The rest of the args
    message="$@"
    echo "Adding project '$message'"
    echo $message >> $CLYDE_PROJ_FILE
    exit 0
fi

# COMMAND: list
if [ $COMMAND == "list" ]; then
    less -FX $CLYDE_PROJ_FILE
    exit 0
fi

# COMMAND: suggest
if [ $COMMAND == "suggest" ]; then
    if [ $SHOW_CLYDE == true ]; then
        showclyde
    fi
    IFS=$'\r\n'
    GLOBIGNORE='*'
    command eval 'projects=($(cat $CLYDE_PROJ_FILE))'
    total=${#projects[@]}

    # $RANDOM generates a number between 0 and 32767
    let "index = $RANDOM % $total"

    echo "CLYDE: Today you should spend time working on this:"
    hr -
    let "num = $index+1"
    echo "#$num: ${projects[$index]}"
    hr -
    exit 0
fi

# COMMAND: manage
if [ $COMMAND == "manage" ]; then
    # Find a suitable text editor
    editor="$VISUAL"
    [ -z "$editor" ] && editor="$EDITOR"
    [ -z "$editor" ] && which editor >/dev/null && editor=editor
    [ -z "$editor" ] && which nano   >/dev/null && editor=nano
    [ -z "$editor" ] && which vi     >/dev/null && editor=vi
    [ -z "$editor" ] && editor=vi

    # Use the editor we found
    $editor "$CLYDE_PROJ_FILE"
    exit 0
fi
